/* Pruebas del recorrido completo. Solo necesitan Playwright para ejecutarse. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const key='tarjeta-joven-demo:v1';
const base=process.env.DEMO_TEST_URL || 'http://localhost:3000';
const screenshots='test-results';
async function main(){
  await fs.mkdir(screenshots,{recursive:true});
  const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:1050},locale:'es-MX'});
  const page=await context.newPage(),errors=[],external=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  page.on('request',request=>{if(!request.url().startsWith(base)&&!request.url().startsWith('data:')&&!request.url().startsWith('blob:'))external.push(request.url());});
  const visit=async route=>{await page.goto(base+'/#'+route,{waitUntil:'networkidle'});await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})));});};
  const data=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
  const click=async name=>page.getByRole('button',{name,exact:true}).click();
  const checkpoint=name=>console.log('PASS '+name);
  try {
    await visit('/');
    assert.match(await page.title(),/Tarjeta Joven/);
    assert.equal(await page.locator('.experience').count(),3);
    await page.locator('.skip-link').focus();
    await page.locator('.skip-link').click();
    assert.equal(await page.evaluate(()=>document.activeElement.id),'main');
    assert.equal(new URL(page.url()).hash,'#/');
    await page.screenshot({path:path.join(screenshots,'01-inicio-escritorio.png'),fullPage:true});
    await visit('/tarjeta');
    await page.screenshot({path:path.join(screenshots,'02-tarjeta-escritorio.png'),fullPage:true});
    await visit('/panel');
    await page.screenshot({path:path.join(screenshots,'03-panel-escritorio.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    for(const route of ['/','/tarjeta','/portal-negocios','/panel','/directorio','/login','/login-negocio']){
      await visit(route);
      const overflow=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,elements:[...document.querySelectorAll('*')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1}).slice(0,10).map(e=>({tag:e.tagName,class:e.className,width:e.getBoundingClientRect().width}))}));
      assert.equal(overflow.overflow,false,'Desbordamiento móvil en '+route+': '+JSON.stringify(overflow.elements));
    }
    await visit('/tarjeta');
    await page.screenshot({path:path.join(screenshots,'04-tarjeta-movil.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1050});
    checkpoint('Inicio, navegación y siete vistas móviles sin desbordamiento');
    await visit('/login');
    const form=page.locator('#youth-form');
    await form.getByLabel('Nombre completo',{exact:true}).fill('Andrea Demo');
    await form.getByLabel('Fecha de nacimiento',{exact:true}).fill((new Date().getFullYear()-20)+'-01-10');
    await form.getByLabel('Correo de ejemplo',{exact:true}).fill('andrea@example.test');
    await form.locator('input[type=checkbox]').check();
    await click('Enviar solicitud de prueba');
    await click('Revisar en administración');
    const request=page.locator('.request-card').filter({hasText:'Andrea Demo'});
    await request.getByRole('button',{name:'Aprobar',exact:true}).click();
    await click('Ver tarjeta');
    let s=await data(),newYouth=s.youths.find(y=>y.name==='Andrea Demo');
    assert.equal(newYouth.status,'Activa');
    assert.notEqual(newYouth.code,s.youths[0].code);
    assert.equal(s.currentYouth,newYouth.id);
    checkpoint('Registro → revisión → aprobación → tarjeta con código único');
    await click('Mi QR');
    await page.addScriptTag({url:base+'/vendor/jsqr.js'});
    const decoded=await page.evaluate(async()=>{
      const svg=document.querySelector('#modal .modal-qr svg').cloneNode(true);
      svg.setAttribute('width','300');svg.setAttribute('height','300');
      const source='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(svg));
      const image=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=source;});
      const canvas=document.createElement('canvas');canvas.width=300;canvas.height=300;
      const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,300,300);ctx.drawImage(image,0,0,300,300);
      const pixels=ctx.getImageData(0,0,300,300);
      return window.jsQR(pixels.data,300,300)?.data;
    });
    assert.equal(decoded,newYouth.code);
    await page.getByRole('button',{name:'Cerrar',exact:true}).click();
    checkpoint('QR real decodificado desde su imagen');
    await visit('/portal-negocios');
    await click('Mis promociones');
    await click('Crear promoción');
    const promoForm=page.locator('#promotion-form');
    await promoForm.getByLabel('Nombre de la promoción',{exact:true}).fill('Beneficio de prueba QA');
    await promoForm.getByLabel('Beneficio visible',{exact:true}).fill('12% OFF');
    await promoForm.getByLabel('Descripción',{exact:true}).fill('Descuento creado para probar la experiencia completa.');
    await promoForm.getByLabel('Días válidos',{exact:true}).selectOption('Todos los días');
    await promoForm.locator('input[name=unique]').check();
    await click('Publicar beneficio');
    s=await data();
    const promo=s.coupons.find(c=>c.title==='Beneficio de prueba QA');
    assert.ok(promo);
    await visit('/tarjeta');
    await page.locator('[data-action=coupon][data-id="'+promo.id+'"]').click();
    await click('Probar validación');
    await click('Registrar visita');
    s=await data();
    assert.equal(s.visits.filter(v=>v.youthId===newYouth.id&&v.couponId===promo.id).length,1);
    await visit('/tarjeta');
    await click('Historial');
    assert.ok((await page.locator('.timeline-content').allTextContents()).some(t=>t.includes('Beneficio de prueba QA')));
    await click('Beneficios');
    await page.locator('[data-action=coupon][data-id="'+promo.id+'"]').click();
    assert.equal(await page.getByRole('button',{name:'Probar validación',exact:true}).isDisabled(),true);
    await page.getByRole('button',{name:'Cerrar',exact:true}).click();
    checkpoint('Publicación → cupón → validación → historial y bloqueo de uso único');
    await page.locator('#profile-select').selectOption('1');
    await visit('/portal-negocios');
    await click('Validar tarjeta');
    if(await page.getByRole('button',{name:'Validar otra tarjeta',exact:true}).count())await click('Validar otra tarjeta');
    await click('Probar QR');
    await click('Registrar visita');
    s=await data();
    assert.equal(s.visits.filter(v=>v.youthId===1).length,3);
    await visit('/tarjeta');
    assert.match(await page.locator('.level-label').innerText(),/Plata/);
    checkpoint('Progresión automática de Clásica a Plata');
    await visit('/portal-negocios');
    await click('Validar otra tarjeta');
    await page.locator('#scan-form input[name=code]').fill('CODIGO-INEXISTENTE');
    await click('Validar código');
    assert.match(await page.locator('.scan-invalid').innerText(),/no pertenece/);
    await page.locator('#scan-form input[name=code]').fill('DEMO-0008');
    await click('Validar código');
    assert.match(await page.locator('.scan-invalid').innerText(),/suspendida/);
    checkpoint('Códigos inexistentes y tarjetas suspendidas rechazados');
    await click('Mis vacantes');
    await click('Crear vacante');
    const jobForm=page.locator('#job-form');
    await jobForm.getByLabel('Nombre de la vacante',{exact:true}).fill('Vacante de prueba QA');
    await jobForm.getByLabel('Sueldo de ejemplo',{exact:true}).fill('$9,000 mensuales');
    await jobForm.getByLabel('Descripción y requisitos',{exact:true}).fill('Oportunidad ficticia para probar el envío de interés.');
    await click('Publicar vacante');
    s=await data();const job=s.jobs.find(j=>j.title==='Vacante de prueba QA');
    await visit('/tarjeta');
    await click('Empleos');
    await page.locator('[data-action=job][data-id="'+job.id+'"]').click();
    await click('Enviar interés de prueba');
    assert.equal(await page.locator('#modal').getByRole('button',{name:'Interés enviado',exact:true}).isDisabled(),true);
    await page.getByRole('button',{name:'Cerrar',exact:true}).click();
    await visit('/portal-negocios');
    await page.locator('[data-action=applicants][data-id="'+job.id+'"]').click();
    assert.match(await page.locator('#modal').innerText(),/Valeria Ruiz/);
    await page.getByRole('button',{name:'Cerrar',exact:true}).click();
    checkpoint('Vacante → interés simulado → lista de interesados del negocio');
    await visit('/panel');
    await click('Avisos');
    await click('Publicar aviso');
    await page.locator('#notice-form').getByLabel('Título',{exact:true}).fill('Aviso QA para jóvenes');
    await page.locator('#notice-form').getByLabel('Mensaje',{exact:true}).fill('Un aviso creado para probar las notificaciones.');
    await page.locator('#notice-form').getByLabel('Dirigido a',{exact:true}).selectOption('Jóvenes');
    await page.locator('#notice-form').getByRole('button',{name:'Publicar aviso',exact:true}).click();
    await visit('/tarjeta');
    await page.locator('[data-action=notices]').click();
    assert.match(await page.locator('#modal').innerText(),/Aviso QA para jóvenes/);
    await page.getByRole('button',{name:'Cerrar',exact:true}).click();
    assert.equal(await page.locator('.notif-count').count(),0);
    checkpoint('Avisos publicados y marcados como leídos');
    await page.getByRole('button',{name:'Personalizar',exact:true}).click();
    await page.locator('#brand-form').getByLabel('Municipio',{exact:true}).fill('Villa de Prueba');
    await page.getByRole('button',{name:'Guinda institucional',exact:true}).click();
    const logo=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAIUlEQVR4AYXBAQEAMAiAME7/zt4Esr1ZHCRIkCBBggQJHxtuBAxSsWhBAAAAAElFTkSuQmCC','base64');
    await page.getByLabel('Subir logo del instituto',{exact:true}).setInputFiles({name:'logo.png',mimeType:'image/png',buffer:logo});
    await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).brand.instituteLogo.startsWith('data:image/png'),key);
    await page.locator('#brand-form').getByRole('button',{name:'Aplicar identidad',exact:true}).click();
    await page.reload({waitUntil:'networkidle'});
    assert.match(await page.title(),/Villa de Prueba/);
    s=await data();
    assert.equal(s.brand.primary,'#702032');
    assert.ok(s.brand.instituteLogo.startsWith('data:image/png'));
    assert.equal(s.visits.filter(v=>v.youthId===1).length,3);
    checkpoint('Municipio, colores, logo y cambios conservados al recargar');
    await visit('/panel');
    await click('Reportes');
    const downloadPromise=page.waitForEvent('download');
    await click('Exportar CSV');
    const download=await downloadPromise;
    await download.saveAs(path.join(screenshots,download.suggestedFilename()));
    const csv=await fs.readFile(path.join(screenshots,download.suggestedFilename()),'utf8');
    assert.ok(csv.includes('Beneficio de prueba QA'));
    assert.ok(csv.includes('Demostración'));
    checkpoint('Reporte CSV con las validaciones registradas');
    await page.locator('[data-action=reset]').click();
    await click('Reiniciar datos de prueba');
    s=await data();
    assert.equal(s.visits.length,8);
    assert.equal(s.brand.municipio,'Villa de Prueba');
    assert.equal(s.youths.some(y=>y.name==='Andrea Demo'),false);
    checkpoint('Reinicio de datos conservando la personalización');
    assert.deepEqual(errors,[]);
    assert.deepEqual(external,[]);
    checkpoint('Sin errores de navegador ni peticiones a servicios externos');
    await fs.writeFile(path.join(screenshots,'verification.json'),JSON.stringify({status:'PASS',checks:12,browser:'Chromium',viewportDesktop:[1440,1050],viewportMobile:[390,844],externalRequests:0,browserErrors:0},null,2));
  } catch(error) {
    await page.screenshot({path:path.join(screenshots,'error.png'),fullPage:true}).catch(()=>{});
    await fs.writeFile(path.join(screenshots,'error.txt'),String(error.stack)+'\nConsole errors: '+JSON.stringify(errors));
    throw error;
  } finally {await browser.close();}
}
main().catch(error=>{console.error(error);process.exit(1)});
